run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - revive
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/domovonok/url-shortener
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-use-default: false
  exclude-rules:
    - path: ^vendor/
      linters: [ all ]
    - path: ".*\\.gen\\.go$"
      linters: [ all ]
