services:
  postgres:
    image: postgres:15
    container_name: url-shortener-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345}
      POSTGRES_DB: ${POSTGRES_DB:-testdb}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  url-shortener:
    image: ${URL_SHORTENER_IMAGE:-ghcr.io/domovonok/url-shortener:latest}
    pull_policy: always
    container_name: url-shortener
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DEBUG: "${DEBUG:-false}"
      HTTP_ADDR: ":8080"
      GRACEFUL_SHUTDOWN_TIMEOUT: "${GRACEFUL_SHUTDOWN_TIMEOUT:-5s}"
      STORAGE_TYPE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "${POSTGRES_DB:-testdb}"
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-12345}"
      POSTGRES_SSL_MODE: "${POSTGRES_SSL_MODE:-disable}"
    ports:
      - "${HTTP_PORT:-8080}:8080"
    networks:
      - backend
    restart: unless-stopped

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
