// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -package get_test -destination mocks/contract_mock.go
//

// Package get_test is a generated GoMock package.
package get_test

import (
	context "context"
	reflect "reflect"

	model "github.com/domovonok/url-shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MocklinkRepo is a mock of linkRepo interface.
type MocklinkRepo struct {
	ctrl     *gomock.Controller
	recorder *MocklinkRepoMockRecorder
	isgomock struct{}
}

// MocklinkRepoMockRecorder is the mock recorder for MocklinkRepo.
type MocklinkRepoMockRecorder struct {
	mock *MocklinkRepo
}

// NewMocklinkRepo creates a new mock instance.
func NewMocklinkRepo(ctrl *gomock.Controller) *MocklinkRepo {
	mock := &MocklinkRepo{ctrl: ctrl}
	mock.recorder = &MocklinkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklinkRepo) EXPECT() *MocklinkRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MocklinkRepo) Get(ctx context.Context, code string) (model.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, code)
	ret0, _ := ret[0].(model.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocklinkRepoMockRecorder) Get(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocklinkRepo)(nil).Get), ctx, code)
}
