// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package urlsqlc

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO url (url)
VALUES ($1)
ON CONFLICT (url) DO NOTHING
RETURNING id
`

func (q *Queries) Create(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRow(ctx, create, url)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const get = `-- name: Get :one
SELECT url
FROM url
WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, get, id)
	var url string
	err := row.Scan(&url)
	return url, err
}

const getIDByURL = `-- name: GetIDByURL :one
SELECT id
FROM url
WHERE url = $1
`

func (q *Queries) GetIDByURL(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRow(ctx, getIDByURL, url)
	var id int64
	err := row.Scan(&id)
	return id, err
}
